# --------------------------
# Secret pour la base de donn√©es
# --------------------------
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: sitepasswordroot
  MYSQL_USER: siteuser
  MYSQL_PASSWORD: sitepassword
