# --------------------------
# Deployment MySQL
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitevitrine-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitevitrine-mysql
  template:
    metadata:
      labels:
        app: sitevitrine-mysql
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found || true"]
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: kayarhabby/sitevitrine-mysql:latest
          envFrom:
            - secretRef:
                name: mysql-secret
          env:
            - name: MYSQL_DATABASE
              value: siteVitrineDB
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
