apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitevitrinemysql
  labels:
    app: sitevitrinemysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sitevitrinemysql
  template:
    metadata:
      labels:
        app: sitevitrinemysql
    spec:
      containers:
        - name: sitevitrinemysql
          image: kayarhabby/sitevitrine-mysql:latest
          envFrom:
           - secretRef:
               name: db-secret
          ports:
            - containerPort: 3306
