apiVersion: v1
kind: Service
metadata:
  name: sitevitrineapp
spec:
  type: clusterIP
  selector:
    app.kubernetes.io/name: sitevitrineapp
  ports:
    - port: 80
      targetPort: 7080
      nodePort: 30007