# --------------------------
# Service MySQL (ClusterIP interne)
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: sitevitrine-mysql-svc
spec:
  type: ClusterIP
  selector:
    app: sitevitrine-mysql
  ports:
    - port: 3306
      targetPort: 3306

