# --------------------------
# Service Application (NodePort)
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: sitevitrineapp
spec:
  type: NodePort
  selector:
    app: sitevitrineapp
  ports:
    - port: 8080        # port interne du Service
      targetPort: 7080  # port du container
      nodePort: 30007   # port externe accessible depuis ton navigateur
