# --------------------------
# Deployment Application Spring Boot
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitevitrine-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sitevitrine-app
  template:
    metadata:
      labels:
        app: sitevitrine-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z sitevitrine-mysql-svc 3306; do
                echo "Waiting for MySQL..."
                sleep 5
              done
      containers:
        - name: app
          image: kayarhabby/sitevitrine-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              ephemeral-storage: 2Gi
            limits:
              ephemeral-storage: 4Gi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sitevitrine-mysql-svc:3306/siteVitrineDB
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD